spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: "root"
    password: "ss"
  cloud:
    task:
      table-prefix: TASK_
      closecontext-enabled: true

springfox:
  documentation:
    swagger-ui:
      enabled: true
    enabled: true
    swagger:
      v2:
        host: "127.0.0.1:9009"

ipLimit: 120